C# dzial handlowy
rudnickirobert/KWZP2022 pull request #126
Opened 2022-05-01 15:12 UTC by jakubkonczyk

2022-05-03 15:21 UTC, rudnickirobert approved these changes

2022-05-03 15:22 UTC, rudnickirobert requested changes
proszę o rozwiązanie konfliktów

2022-05-04 16:34 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormNewCommertialOffer.cs
> +                goto EndLoop;
programowanie obiektowe, nie proceduralne- nie stosujemy `goto` (podpowiedź: z petli mozna wyjsc innym sposobem)

2022-05-05 08:44 UTC, rudnickirobert commented
proszę o rozwiązanie konfliktów

2022-05-08 19:47 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/FormNewCommertialOffer.cs
> +                goto EndLoop;
Poprawiono

2022-05-09 11:03 UTC, rudnickirobert approved these changes

2022-05-09 11:03 UTC, merged