Added new forms related to adding new types
rudnickirobert/KWZP2022 pull request #130
Opened 2022-05-05 20:27 UTC by PodSZ

2022-05-06 09:27 UTC, rudnickirobert requested changes
proszę rozwiązać konflikty

2022-05-06 13:53 UTC, rudnickirobert requested changes

2022-05-06 13:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDepMaterial.cs
> +        private void button1_Click(object sender, EventArgs e)
nazwa przycisku

2022-05-06 19:20 UTC, domin1107 commented on KWZP2022/KWZP2022/FormResDepMaterial.cs
> +        private void button1_Click(object sender, EventArgs e)
zmieniono

2022-05-09 11:04 UTC, rudnickirobert commented
proszę rozwiązać konflikty

2022-05-10 06:45 UTC, rudnickirobert approved these changes

2022-05-10 06:47 UTC, merged