Multiple production for the same order
rudnickirobert/KWZP2022 pull request #131
Opened 2022-05-06 10:42 UTC by Czernich

2022-05-06 13:53 UTC, rudnickirobert requested changes

2022-05-06 13:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +/*                int iloscProduktowKolejka = int.Parse(dgvvKontrolaJakosciKolejka.RowCount.ToString());
do usunięcia

2022-05-06 16:45 UTC, arek4802 commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +/*                int iloscProduktowKolejka = int.Parse(dgvvKontrolaJakosciKolejka.RowCount.ToString());
👍

2022-05-10 06:47 UTC, rudnickirobert commented
proszę rozwiązać konflikty

2022-05-11 07:58 UTC, rudnickirobert approved these changes

2022-05-11 07:58 UTC, merged