Hr overtime
rudnickirobert/KWZP2022 pull request #143
Opened 2022-05-12 11:16 UTC by duszynpawel

2022-05-12 12:27 UTC, rudnickirobert requested changes

2022-05-12 12:27 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentNewSalary.cs
> +        //private void showData()
do usunięcia

2022-05-12 12:33 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentNewSalary.cs
> +        //private void showData()
Naprawione

2022-05-13 06:15 UTC, rudnickirobert approved these changes

2022-05-13 06:15 UTC, merged