Cs
rudnickirobert/KWZP2022 pull request #19
Opened 2022-04-19 17:11 UTC by Czernich

2022-04-19 18:26 UTC, rudnickirobert requested changes

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/Dzial_produkcyjnyForm.cs
> +        KWZPEntities db = new KWZPEntities();
nie tworzymy nowego obiektu w kiolejnych formularzach

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +                int name2 = data.Count();
proszę o znaczącą nazwę zmiennej

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +            textBoxNo2.Clear();
czym są `textBoxNo1` i `textBoxNo2`?

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +            if (textBox2Name.Text.Length > 0 && textBox1Name.Text.Length == 0 && textBoxNIP.Text.Length == 0 && textBoxCity.Text.Length == 0 && textBoxNo1.Text.Length == 0 && textBoxNo2.Text.Length =
każdy z warunków proszę wydzielić do osobnej metody (po nazwie będzie widać co jest sprawdzane) a tutaj zamiast drzewa ifów użyć switch/case

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +                    messageBox();
ten zestaw metod się powtarza zatem proszę wydzielić do osobnej metody

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +                    var data = dataSearch.Where(a => a.Numer_budynku > 0).Count();
nazwa zmiennej, wszystko wyzej i nizej moze byc `data`

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +                var data = db.v_Klient.Where(a => a.Nazwisko == textBox2Name.Text);
nazwa zmiennej, wszystko wyzej i nizej moze byc `data`

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +                    int textINT = int.Parse(text);
nazwy

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClientNewClient.cs
> +            //if (textBox1Name.Text.Length > 0 && textBox2Name.Text.Length > 0 && textBoxCity.Text.Length > 0 && textBoxNIP.Text.Length > 0 && textBoxNo1.Text.Length > 0 && textBoxNo2.Text.Length > 0
skoro kod nie działa to nie jest nam potrzebny, do usunięcia

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClientNewClient.cs
> +            textBox1Name.Clear();
czym jest to pole?

2022-04-19 18:26 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentSales.cs
> +                var data = db.v_Sprzedaz.Where(a => a.Imię_klienta == textBox1Name.Text);
jw

2022-04-19 22:32 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +            textBoxNo2.Clear();
textBoxNo1 - Numer budynku
textBoxNo2 - Numer lokalu
No - skrót od Number

2022-04-20 08:22 UTC, rudnickirobert submitted a review, later dismissed

2022-04-20 08:42 UTC, rudnickirobert approved these changes

2022-04-20 08:56 UTC, merged