Corrected Insert Stanowisko_produkcyjne, Wytwarzanie
rudnickirobert/KWZP2022 pull request #32
Opened 2022-04-20 16:25 UTC by arek4802

Adding Insert Kontrola_parametr

2022-04-20 16:31 UTC, rudnickirobert requested changes

2022-04-20 16:31 UTC, rudnickirobert commented on ddl.sql
> +--rDROP DATABASE KWZP
proszę o przywrócenie właściwej wersji

2022-04-20 18:12 UTC, arek4802 reviewed
Fixed bugs

2022-04-20 18:23 UTC, rudnickirobert requested changes

2022-04-20 18:23 UTC, rudnickirobert commented on dql.sql
> +--CREATE VIEW v_Magazyn_material_wszystko
nie commitujemy zakomentowanego kodu

2022-04-20 18:33 UTC, PodSZ commented on dql.sql
> +--CREATE VIEW v_Magazyn_material_wszystko
Poprawione

2022-04-21 06:32 UTC, rudnickirobert approved these changes

2022-04-21 06:33 UTC, merged