Added table "Czas_pracy ", added inserts into table and created view …
rudnickirobert/KWZP2022 pull request #35
Opened 2022-04-20 19:01 UTC by sylwiamarcinkiewicz

…"v_Koszt_godziny_pracy"

2022-04-21 06:38 UTC, rudnickirobert approved these changes

2022-04-21 06:38 UTC, rudnickirobert commented
proszę o rozwiązanie konfliktów

2022-04-21 20:28 UTC, rudnickirobert requested changes
proszę o rozwiązanie konfliktów

2022-04-21 20:52 UTC, MGawron1998 commented
Resolved a conflict

2022-04-22 06:10 UTC, rudnickirobert approved these changes

2022-04-22 06:10 UTC, merged