Res dep cs
rudnickirobert/KWZP2022 pull request #36
Opened 2022-04-20 20:34 UTC by domin1107

Added ZamowienieFORM and MagazynFORM

2022-04-21 06:40 UTC, rudnickirobert requested changes

2022-04-21 06:40 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartment.cs
> +        private void FormSalesDepartment_Load(object sender, EventArgs e)
ta medota nic nie robi, do usunięcia

2022-04-21 06:40 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartment.cs
> +        private void btnOrder_Click(object sender, EventArgs e)
ta medota nic nie robi, do usunięcia

2022-04-21 06:40 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormDepartments.cs
> +        private void FormDepartments_Load(object sender, EventArgs e)
ta medota nic nie robi, do usunięcia

2022-04-21 06:40 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClientModifyClient.cs
>              textBoxNo2.Text = daneKlientDaneAdresowe.Nr_lokal.ToString();
proszę o zmianę nazwy na znaczącą `textBoxNo2`

2022-04-21 06:40 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClientModifyClient.cs
> +                catch (Exception)
dlaczego łapiemy wszystkie wyjątki?

2022-04-21 06:40 UTC, rudnickirobert commented on KWZP2022/KWZP2022/ResDepFORMMagazyn.cs
> +        private void ResDepFORMMagazyn_Load(object sender, EventArgs e)
do usunięcia puste metody

2022-04-21 06:40 UTC, rudnickirobert commented on KWZP2022/KWZP2022/ZamowieniaResDepFORM.cs
> +        private void ZamowieniaResDepFORM_Load(object sender, EventArgs e)
jw

2022-04-21 20:31 UTC, rudnickirobert requested changes

2022-04-21 20:31 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDep.cs
> +    public partial class FormResDep : Form
proszę o zmianę nazwy formularza na znaczącą, przy gigabajtach pamięci RAM i ekranach 4k nie musimy się martwić o pojedyncze litery

2022-04-21 20:31 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDepZamowienia.cs
> +            FormResDepZamowienieCzesci zamowienia_czesciFrom = new FormResDepZamowienieCzesci(db);
nazwy obiektow piszemy camelCase

2022-04-21 20:31 UTC, rudnickirobert commented on KWZP2022/KWZP2022/ProduktForm.cs
> +        private void ProduktForm_Load(object sender, EventArgs e)
do usunięcia

2022-04-23 10:46 UTC, szymk1 commented on KWZP2022/KWZP2022/ProduktForm.cs
> +        private void ProduktForm_Load(object sender, EventArgs e)
zrobione

2022-04-23 10:46 UTC, szymk1 commented on KWZP2022/KWZP2022/FormResDepZamowienia.cs
> +            FormResDepZamowienieCzesci zamowienia_czesciFrom = new FormResDepZamowienieCzesci(db);
zrobione

2022-04-23 10:46 UTC, szymk1 commented on KWZP2022/KWZP2022/FormResDep.cs
> +    public partial class FormResDep : Form
zrobione

2022-04-23 10:47 UTC, szymk1 commented on KWZP2022/KWZP2022/ZamowieniaResDepFORM.cs
> +        private void ZamowieniaResDepFORM_Load(object sender, EventArgs e)
zrobione

2022-04-23 10:47 UTC, szymk1 commented on KWZP2022/KWZP2022/ResDepFORMMagazyn.cs
> +        private void ResDepFORMMagazyn_Load(object sender, EventArgs e)
zrobione

2022-04-23 10:47 UTC, szymk1 commented on KWZP2022/KWZP2022/FormSalesDepartmentClientModifyClient.cs
>              textBoxNo2.Text = daneKlientDaneAdresowe.Nr_lokal.ToString();
zrobione

2022-04-23 10:47 UTC, szymk1 commented on KWZP2022/KWZP2022/FormDepartments.cs
> +        private void FormDepartments_Load(object sender, EventArgs e)
zrobione

2022-04-23 10:47 UTC, szymk1 commented on KWZP2022/KWZP2022/FormSalesDepartment.cs
> +        private void FormSalesDepartment_Load(object sender, EventArgs e)
zrobione

2022-04-23 13:50 UTC, rudnickirobert approved these changes

2022-04-23 13:50 UTC, merged