Dodanie formularza do wiazania produktu z polproduktami
rudnickirobert/KWZP2022 pull request #37
Opened 2022-04-21 11:12 UTC by Czernich

2022-04-21 15:16 UTC, rudnickirobert requested changes

2022-04-21 15:16 UTC, rudnickirobert commented on KWZP2022/KWZP2022/PolproduktForm.cs
> +            Sklad_produkt skladProdukt = new Sklad_produkt();
proszę również o zmianę nazwy formularza na `FormPolprodukt`

2022-04-21 19:26 UTC, Czernich commented on KWZP2022/KWZP2022/PolproduktForm.cs
> +            Sklad_produkt skladProdukt = new Sklad_produkt();
Nazwa formularza zmieniona, przycisk aktualizuj wyrzucilem z użycia. W przypadku tego formularza tylko by utrudnił korzystanie z aplikacji.

2022-04-21 20:33 UTC, rudnickirobert requested changes

2022-04-21 20:33 UTC, rudnickirobert commented on KWZP2022/KWZP2022/PolproduktDodanieForm.cs
> +            bool found = new bool();
`bool found = false`

2022-04-21 20:33 UTC, rudnickirobert commented on KWZP2022/KWZP2022/PolproduktDodanieForm.cs
> +            if (found == false)
proszę odwrócić ifa i wtedy ` if (found)`

2022-04-21 20:33 UTC, rudnickirobert commented on KWZP2022/KWZP2022/PolproduktDodanieForm.cs
> +                if (txtPolprodukt.Enabled = false)
tu następuje przypisanie wartości a nie jej sprawdzenie

2022-04-22 07:07 UTC, Czernich commented on KWZP2022/KWZP2022/PolproduktDodanieForm.cs
> +            bool found = new bool();
Poprawione

2022-04-22 07:07 UTC, Czernich commented on KWZP2022/KWZP2022/PolproduktDodanieForm.cs
> +            if (found == false)
Poprawione

2022-04-22 07:07 UTC, Czernich commented on KWZP2022/KWZP2022/PolproduktDodanieForm.cs
> +                if (txtPolprodukt.Enabled = false)
Poprawione

2022-04-22 07:25 UTC, rudnickirobert approved these changes

2022-04-22 07:25 UTC, rudnickirobert commented
proszę w następnym PR zmienić nazwy formularzy tak aby zaczynały się od `Form`

2022-04-22 07:25 UTC, merged