Cs malecki rybarczyk
rudnickirobert/KWZP2022 pull request #40
Opened 2022-04-21 11:31 UTC by Malczi

2022-04-21 15:20 UTC, rudnickirobert requested changes

2022-04-21 15:20 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +            var datavOrders = from v_Zamowienie in db.v_Zamowienie
zamiast `var` typ i widok

2022-04-21 15:20 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +                System.Linq.IQueryable vOrderId = db.v_Zamowienie.Cast<v_Zamowienie>().Where(a => a.Nr_zamówienia == idOrderInt);
po co `Cast`?

2022-04-21 15:20 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +                choose = "IdOrder";
nic się z tym dalej nie dzieje

2022-04-21 15:20 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +        private void label1_Click(object sender, EventArgs e)
do usunięcia

2022-04-21 15:20 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +        private void button1_Click(object sender, EventArgs e)
nazwa przycisku

2022-04-22 19:51 UTC, Malczi commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +        private void button1_Click(object sender, EventArgs e)
poprawiono

2022-04-22 19:52 UTC, Malczi commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +        private void label1_Click(object sender, EventArgs e)
usunięto

2022-04-22 19:52 UTC, Malczi commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +                choose = "IdOrder";
jest już okey

2022-04-22 19:53 UTC, Malczi commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +                System.Linq.IQueryable vOrderId = db.v_Zamowienie.Cast<v_Zamowienie>().Where(a => a.Nr_zamówienia == idOrderInt);
Cast został wyeliminowany z niepotrzebnych fragmentów

2022-04-22 19:53 UTC, Malczi commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +            var datavOrders = from v_Zamowienie in db.v_Zamowienie
poprawiono

2022-04-22 19:53 UTC, Malczi commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +        private void msgCleanShowData()
zastosowano clear

2022-04-23 13:53 UTC, rudnickirobert requested changes
proszę rozwiązać konflikty

2022-04-23 13:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentDetailsOrder.cs
> +        private void Data()
nazwy metod piszemy z małej litery

2022-04-23 13:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentDetailsOrder.cs
> +        private void Data()
proponuję nazwę `initDetails`

2022-04-23 13:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentOffersOrder.cs
> +        private void Data()
jdw

2022-04-23 13:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +            if (textBox2Name.Text.Length > 0)
`textBox2Name` - rozmawialiśmy o zmianie nazwy tej zmiennej

2022-04-23 14:48 UTC, danielrybarczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentDetailsOrder.cs
> +        private void Data()
Poprawiono

2022-04-23 14:48 UTC, danielrybarczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentOffersOrder.cs
> +        private void Data()
Poprawiono

2022-04-23 14:48 UTC, danielrybarczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentOrders.cs
> +            if (textBox2Name.Text.Length > 0)
Poprawiono

2022-04-23 20:17 UTC, closed without merging