Add Form ParametrProdukt
rudnickirobert/KWZP2022 pull request #52
Opened 2022-04-22 14:03 UTC by arek4802

2022-04-23 13:58 UTC, rudnickirobert requested changes

2022-04-23 13:58 UTC, rudnickirobert commented on KWZP2022/KWZP2022/ParametrPolproduktForm.cs
> +    public partial class ParametrPolproduktForm : Form
proszę o zmianę nazwy formularza na `FormParametrPolprodukt`

2022-04-23 13:58 UTC, rudnickirobert commented on KWZP2022/KWZP2022/ParametrPolproduktForm.cs
> +            //dgvPolprodukt.Columns["Sklad_produkt_material"].Visible = false;
do usunięcia

2022-04-23 13:58 UTC, rudnickirobert commented on KWZP2022/KWZP2022/ParametrProduktForm.cs
> +                var result = db.Parametr_produkt.SingleOrDefault(b => b.ID_parametr_produkt == currentID);
nie używamy `var`

2022-04-23 13:58 UTC, rudnickirobert commented on KWZP2022/KWZP2022/ParametrProduktForm.cs
> +    public partial class ParametrProduktForm : Form
jw nazwa formularza

2022-04-23 13:58 UTC, rudnickirobert commented on KWZP2022/KWZP2022/PolproduktDodanieForm.cs
> +        private void btnDodajParametrProdukt_Click(object sender, EventArgs e)
jw nazwa formularza

2022-04-23 13:58 UTC, rudnickirobert commented on KWZP2022/KWZP2022/ProduktForm.cs
>          private void btnUsun_Click(object sender, EventArgs e)
jw nazwa formularza

2022-04-23 14:45 UTC, arek4802 commented on KWZP2022/KWZP2022/ParametrPolproduktForm.cs
> +    public partial class ParametrPolproduktForm : Form
poprawione

2022-04-23 14:45 UTC, arek4802 commented on KWZP2022/KWZP2022/ParametrPolproduktForm.cs
> +            //dgvPolprodukt.Columns["Sklad_produkt_material"].Visible = false;
poprawione

2022-04-23 14:46 UTC, arek4802 commented on KWZP2022/KWZP2022/ParametrProduktForm.cs
> +    public partial class ParametrProduktForm : Form
poprawione

2022-04-23 14:46 UTC, arek4802 commented on KWZP2022/KWZP2022/PolproduktDodanieForm.cs
> +        private void btnDodajParametrProdukt_Click(object sender, EventArgs e)
poprawione

2022-04-23 14:46 UTC, arek4802 commented on KWZP2022/KWZP2022/ProduktForm.cs
>          private void btnUsun_Click(object sender, EventArgs e)
poprawione

2022-04-23 15:47 UTC, arek4802 commented on KWZP2022/KWZP2022/ParametrProduktForm.cs
> +                var result = db.Parametr_produkt.SingleOrDefault(b => b.ID_parametr_produkt == currentID);
zrobione

2022-04-25 06:29 UTC, rudnickirobert requested changes

2022-04-25 06:29 UTC, rudnickirobert commented on KWZP2022/KWZP2022/App.config
> +  <add name="KWZPEntities" connectionString="metadata=res://*/KWZPModel.csdl|res://*/KWZPModel.ssdl|res://*/KWZPModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=M
nie zmieniamy nazwy bazy oraz hasła

2022-04-25 06:37 UTC, arek4802 commented on KWZP2022/KWZP2022/App.config
> +  <add name="KWZPEntities" connectionString="metadata=res://*/KWZPModel.csdl|res://*/KWZPModel.ssdl|res://*/KWZPModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=M
poprawione

2022-04-25 06:41 UTC, arek4802 commented
poprawione

2022-04-25 06:56 UTC, rudnickirobert approved these changes

2022-04-25 06:56 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +        private void initDataGridViewKontrolaProdukt()
to niepotrzebnie doszło :)

2022-04-25 06:57 UTC, merged

2022-04-25 07:00 UTC, arek4802 commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +        private void initDataGridViewKontrolaProdukt()
Po prostu byłem w trakcie robienia