Sql
rudnickirobert/KWZP2022 pull request #6
Opened 2022-04-13 18:56 UTC by Czernich

2022-04-14 06:03 UTC, rudnickirobert requested changes

2022-04-14 06:03 UTC, rudnickirobert commented on dml.sql
> +('1','6',1),
czemu `string`? pole powinno być typu `int`

2022-04-14 06:03 UTC, rudnickirobert commented on dml.sql
> +(1,3,45,50),
wiekszość półproduktów ma tylko jeden parametr?

2022-04-14 06:03 UTC, rudnickirobert commented on dml.sql
> +(1,5,2),
jw

2022-04-14 06:03 UTC, rudnickirobert commented on dml.sql
> +('000-001'),
czy to jest słownik numerów seryjnych?

2022-04-14 06:03 UTC, rudnickirobert commented on dml.sql
> +--INSERT INTO Zamowienie (ID_klient, ID_pracownik, Data_zamowienie, ID_typ_zamowienie)
nie commitujemy zakomentowanego kodu

2022-04-14 06:03 UTC, rudnickirobert commented on dml.sql
> +--INSERT INTO Oferta_handlowa (ID_zamowienie, ID_pracownik, ID_produkt, Termin_realizacja, ID_gwarancja, ID_status_oferta, Ilosc)
jw

2022-04-14 06:03 UTC, rudnickirobert commented on dml.sql
> +--INSERT INTO Umowa_sprzedaz (ID_oferta_handlowa)
jw

2022-04-14 10:48 UTC, rudnickirobert requested changes

2022-04-14 10:48 UTC, rudnickirobert commented on ddl.sql
> +--DROP DATABASE KWZP
to powinno zostać

2022-04-14 10:48 UTC, rudnickirobert commented on ddl.sql
> +	Wynik NVARCHAR(50) NOT NULL,
to będzie wynikać już z dokonanych pomiarów i tolerancji, nie potrzebujemy tabeli

2022-04-15 15:16 UTC, rudnickirobert approved these changes

2022-04-15 15:17 UTC, rudnickirobert requested changes
proszę o poprawienie uwag

2022-04-19 07:06 UTC, rudnickirobert requested changes
bardzo proszę o **PILNE** poprawieinie wszystkich uwag

2022-04-19 07:06 UTC, rudnickirobert commented on ddl.sql
> +		CONSTRAINT PK_ParamPro PRIMARY KEY (ID_produkt, ID_rodzaj_parametr)
proszę o weryfikację poprawności działania w entity framework

2022-04-19 07:06 UTC, rudnickirobert commented on ddl.sql
> +		CONSTRAINT PK_ParamPolPro PRIMARY KEY (ID_polprodukt, ID_rodzaj_parametr)
proszę o weryfikację poprawności działania w entity framework

2022-04-19 07:06 UTC, rudnickirobert commented on ddl.sql
> +	ID_oferta_handlowa INT FOREIGN KEY
tu powinien być odnośnik do szczegółów oferty

2022-04-20 07:34 UTC, Czernich commented on ddl.sql
> +		CONSTRAINT PK_ParamPro PRIMARY KEY (ID_produkt, ID_rodzaj_parametr)
Dodalismy klucz podstawowy i usunęliśmy constraint

2022-04-20 07:34 UTC, Czernich commented on ddl.sql
> +		CONSTRAINT PK_ParamPolPro PRIMARY KEY (ID_polprodukt, ID_rodzaj_parametr)
Dodalismy klucz podstawowy i usunęliśmy constraint

2022-04-20 08:21 UTC, rudnickirobert approved these changes

2022-04-20 08:21 UTC, merged