Prod dep czernichowski
rudnickirobert/KWZP2022 pull request #62
Opened 2022-04-23 15:10 UTC by Czernich

2022-04-23 16:08 UTC, rudnickirobert requested changes
proszę o rozwiązanie konfliktów

2022-04-25 06:31 UTC, rudnickirobert requested changes

2022-04-25 06:31 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormCzasPracyProdukcja.cs
> +            var czasOd = dtpCzasOd.Value.Date;
nie używamy `var`

2022-04-25 06:31 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +        private void dgvSkladProdukt_CellContentClick(object sender, DataGridViewCellEventArgs e)
do usunięcia

2022-04-25 06:31 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormWytwarzanie.cs
> +
puste linie do usunięcia

2022-04-25 07:02 UTC, Czernich commented on KWZP2022/KWZP2022/FormCzasPracyProdukcja.cs
> +            var czasOd = dtpCzasOd.Value.Date;
Usunięte

2022-04-25 07:03 UTC, Czernich commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +        private void dgvSkladProdukt_CellContentClick(object sender, DataGridViewCellEventArgs e)
Usunięte

2022-04-25 07:03 UTC, Czernich commented on KWZP2022/KWZP2022/FormWytwarzanie.cs
> +
Usunięte

2022-04-25 07:44 UTC, rudnickirobert commented
proszę o rozwiązanie konfliktów

2022-04-25 09:17 UTC, Czernich commented
Gotowe do mergowania.

2022-04-25 09:37 UTC, rudnickirobert requested changes

2022-04-25 09:37 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +        private void dgvSkladProdukt_CellContentClick(object sender, DataGridViewCellEventArgs e)
nie wygląda

2022-04-25 09:37 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +
puste linie do usunięcia

2022-04-25 09:37 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +                dgvCzynnosciProdukcyjne.DataSource = vCzynnosci.Cast< v_Koszt_procesow_polprodukt> ().ToList();
o rzutowaniu porozmawiamy na zajęciach

2022-04-25 09:37 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +            dgvCzynnosciProdukcyjne.DataSource = null;
dla `vCzynnosciInt == 0` datasource bedzie nullem, na pewno tak ma być?

2022-04-25 09:37 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormWytwarzanie.cs
> +                int wytID = (from n in db.Wytwarzanie orderby n.ID_wytwarzanie descending select n.ID_wytwarzanie).FirstOrDefault();
nie oszczędzamy znaków na nazwach

2022-04-25 09:42 UTC, Czernich commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +            dgvCzynnosciProdukcyjne.DataSource = null;
W przypadku zmiany pracownika i pojawienia się takiego, który nie ma rekordów w tym dgv zostają rekordy z pracownika poprzedniego. Taki zabieg gwarantuje wyczyszczenie dgv.

2022-04-25 09:43 UTC, Czernich commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +                dgvCzynnosciProdukcyjne.DataSource = vCzynnosci.Cast< v_Koszt_procesow_polprodukt> ().ToList();
Czyli na ten moment mogę zakomentować kod?

2022-04-25 09:46 UTC, Czernich commented on KWZP2022/KWZP2022/FormWytwarzanie.cs
> +                int wytID = (from n in db.Wytwarzanie orderby n.ID_wytwarzanie descending select n.ID_wytwarzanie).FirstOrDefault();
Poprawione

2022-04-25 09:47 UTC, Czernich commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +
Usunięte

2022-04-25 09:47 UTC, Czernich commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +            dgvCzynnosciProdukcyjne.DataSource = null;
Pozostawiam bez zmian

2022-04-25 09:47 UTC, Czernich commented on KWZP2022/KWZP2022/FormKosztProdukcja.cs
> +                dgvCzynnosciProdukcyjne.DataSource = vCzynnosci.Cast< v_Koszt_procesow_polprodukt> ().ToList();
Kod zakomentowany do konsultacji.

2022-04-25 10:11 UTC, merged