C# new commertial offer
rudnickirobert/KWZP2022 pull request #66
Opened 2022-04-23 20:36 UTC by jakubkonczyk

2022-04-25 06:35 UTC, rudnickirobert approved these changes

2022-04-25 06:36 UTC, rudnickirobert requested changes
proszę o rozwiązanie konfliktów

2022-04-25 11:00 UTC, jakubkonczyk commented
Konflikty zostały rozwiązane

2022-04-25 11:50 UTC, rudnickirobert requested changes

2022-04-25 11:50 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentAddSales.cs
> +        private void button1_Click(object sender, EventArgs e)
nazwa buttona

2022-04-25 11:50 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +                System.Linq.IQueryable vClientNoApartment = db.v_Klient.Where(a => a.Numer_lokalu == noApartmentInt);
`System.Linq.IQueryable` mozna zmienic na `List<v_Klient>`

2022-04-25 11:50 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentAddSales.cs
> +            var unSoldOrders = from unSoldOrdersView in db.v_Sprzedane_zamowienia_form
nie używamy `var`

2022-04-25 11:50 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentAddSales.cs
> +            var unSoldOrders = from unSoldOrdersView in db.v_Sprzedane_zamowienia_form
nazwa zmiennej mowi odwrotnosc nazwy widoku

2022-04-25 11:50 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormNewOrder.cs
> +                int selectedTyp_ZamowienieInt = int.Parse(comboBoxOrderType.SelectedValue.ToString());
nazwy zmiennych piszemy camelCase, dotyczy tez wszsykich nizej

2022-04-25 12:27 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentAddSales.cs
> +        private void button1_Click(object sender, EventArgs e)
Poprawiono

2022-04-25 12:27 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentClient.cs
> +                System.Linq.IQueryable vClientNoApartment = db.v_Klient.Where(a => a.Numer_lokalu == noApartmentInt);
Poprawiono

2022-04-25 12:27 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentAddSales.cs
> +            var unSoldOrders = from unSoldOrdersView in db.v_Sprzedane_zamowienia_form
Poprawiono

2022-04-25 12:27 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/FormNewOrder.cs
> +                int selectedTyp_ZamowienieInt = int.Parse(comboBoxOrderType.SelectedValue.ToString());
Poprawiono

2022-04-25 14:53 UTC, rudnickirobert requested changes

2022-04-25 14:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentSales.cs
> +            var data = db.v_Sprzedaz.Where(a => a.Nazwisko_klienta == textBox2Name.Text);
nadal `var`

2022-04-25 14:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentSales.cs
> +            int name2 = data.Count();
nazwa zmiennej

2022-04-25 14:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentSales.cs
> +            textBox2Name.Clear();
nazwy textboxow

2022-04-25 14:53 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentSales.cs
> +            var data = db.v_Sprzedaz.Where(a => a.Imię_klienta == textBox1Name.Text);
jw

2022-04-25 17:20 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentSales.cs
> +            var data = db.v_Sprzedaz.Where(a => a.Imię_klienta == textBox1Name.Text);
Poprawiono

2022-04-26 06:49 UTC, rudnickirobert requested changes

2022-04-26 06:49 UTC, rudnickirobert commented on KWZP2022/KWZP2022/Form1.cs
> +            FormNewOrder formNewOreder = new FormNewOrder(db);
literówka

2022-04-26 06:49 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +            int vProduktIdInt = vProdukt.Cast<v_Parametry_produkt>().Where(a => a.ID_produkt > 0).Count();
dlaczego sprawdzamy czy wartość rekordu jest większa od 0?

2022-04-26 06:49 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +            //int numRows = dgvvKontrolaJakosciKolejka.Rows.Count;
do usunięcia

2022-04-26 06:49 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSalesDepartmentSales.cs
> +            var dataSales = from salesView in this.db.v_Sprzedaz
nie używamy `var`

2022-04-26 20:51 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/Form1.cs
> +            FormNewOrder formNewOreder = new FormNewOrder(db);
Poprawiono

2022-04-26 20:51 UTC, jakubkonczyk commented on KWZP2022/KWZP2022/FormSalesDepartmentSales.cs
> +            var dataSales = from salesView in this.db.v_Sprzedaz
Poprawiono

2022-04-26 21:03 UTC, arek4802 commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +            int vProduktIdInt = vProdukt.Cast<v_Parametry_produkt>().Where(a => a.ID_produkt > 0).Count();
poprawione

2022-04-26 21:04 UTC, arek4802 commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +            //int numRows = dgvvKontrolaJakosciKolejka.Rows.Count;
poprawione

2022-04-27 06:07 UTC, rudnickirobert requested changes

2022-04-27 06:07 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +            int vProduktIdInt = vProdukt.Cast<v_Parametry_produkt>().Where(a => a.ID_produkt > 0).Count();
nadal sprawdzamy

2022-04-27 06:07 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +                dgvvParametrProdukt.DataSource = vProdukt.Cast<v_Parametry_produkt>().ToList();
cast do usunięcia

2022-04-27 06:07 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormKontrolaJakosci.cs
> +            //int numRows = dgvvKontrolaJakosciKolejka.Rows.Count;
nadal jest

2022-04-27 06:07 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormNewOrder.cs
> +                    Pracownik selectedEmpployee = this.db.Pracownik.Single(a => a.ID_pracownik == selectedEmpployeeInt);
literówka

2022-04-27 06:07 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormProdukt.cs
> +            //FormSkladProduktMaterial skladproduktmaterialForm = new FormSkladProduktMaterial(db);
do usuniecia

2022-04-27 06:34 UTC, Malczi commented on KWZP2022/KWZP2022/FormNewOrder.cs
> +                    Pracownik selectedEmpployee = this.db.Pracownik.Single(a => a.ID_pracownik == selectedEmpployeeInt);
poprawiono

2022-04-27 08:20 UTC, rudnickirobert approved these changes

2022-04-27 08:20 UTC, merged