Res dep status
rudnickirobert/KWZP2022 pull request #85
Opened 2022-04-26 14:47 UTC by szymk1

2022-04-26 20:21 UTC, rudnickirobert requested changes

2022-04-26 20:21 UTC, rudnickirobert commented on KWZP2022/KWZP2022/App.config
> + <add name="KWZPEntities" connectionString="metadata=res://*/KWZPModel.csdl|res://*/KWZPModel.ssdl|res://*/KWZPModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=DE
nie modyfikujemy

2022-04-26 20:21 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDepServices.cs
> +            FormResDepServicesAdd nowaoblsugaForm = new FormResDepServicesAdd(db);
literowka i poprawka camelCase

2022-04-26 20:21 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDepServicesExchanged.cs
> +                    dgvCzesci.DataSource = skladMaszyna.Cast<v_Sklad_maszyna>().ToList();
`Cast` do usunięcia

2022-04-26 20:21 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDepServicesWorkers.cs
> +            dgvObsluga.DataSource = pracownikObsluga.Cast<v_Obsluga_pracownik>().ToList();
`Cast` do usunięcia

2022-04-26 21:31 UTC, domin1107 commented on KWZP2022/KWZP2022/App.config
> + <add name="KWZPEntities" connectionString="metadata=res://*/KWZPModel.csdl|res://*/KWZPModel.ssdl|res://*/KWZPModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=DE
poprawiono

2022-04-26 21:31 UTC, domin1107 commented on KWZP2022/KWZP2022/FormResDepServices.cs
> +            FormResDepServicesAdd nowaoblsugaForm = new FormResDepServicesAdd(db);
poprawiono

2022-04-26 21:31 UTC, domin1107 commented on KWZP2022/KWZP2022/FormResDepServicesExchanged.cs
> +                    dgvCzesci.DataSource = skladMaszyna.Cast<v_Sklad_maszyna>().ToList();
poprawiono

2022-04-26 21:31 UTC, domin1107 commented on KWZP2022/KWZP2022/FormResDepServicesWorkers.cs
> +            dgvObsluga.DataSource = pracownikObsluga.Cast<v_Obsluga_pracownik>().ToList();
poprawiono

2022-04-27 06:13 UTC, rudnickirobert requested changes

2022-04-27 06:13 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDepServicesAdd.cs
> +            if (cmbObsluga.Text != "Wymiana czesci")
`btnDodajWymiana.Visible = cmbObsluga.Text == "Wymiana czesci";`

2022-04-27 06:13 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDepServicesExchanged.cs
> +                MessageBox.Show("CO SIĘ ODPIERDALAAA");
ekhm

2022-04-27 06:13 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormResDepServicesWorkers.cs
> +            //dgvObsluga.Columns[0].Visible = false;
do usuniecia

2022-04-27 06:36 UTC, szymk1 commented on KWZP2022/KWZP2022/FormResDepServicesWorkers.cs
> +            //dgvObsluga.Columns[0].Visible = false;
poprawione

2022-04-27 06:36 UTC, szymk1 commented on KWZP2022/KWZP2022/FormResDepServicesExchanged.cs
> +                MessageBox.Show("CO SIĘ ODPIERDALAAA");
poprawione

2022-04-27 06:36 UTC, szymk1 commented on KWZP2022/KWZP2022/FormResDepServicesAdd.cs
> +            if (cmbObsluga.Text != "Wymiana czesci")
poprawione

2022-04-27 06:50 UTC, rudnickirobert approved these changes

2022-04-27 06:50 UTC, merged