Gawron_HR
rudnickirobert/KWZP2022 pull request #87
Opened 2022-04-26 16:15 UTC by MGawron1998

2022-04-26 20:25 UTC, rudnickirobert requested changes

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +            if (tbPracownikNazwisko.Text.Length > 0 && tbPracownikImie.Text.Length > 0 && tbNrdowodu.Text.Length > 0 && tbPesel.Text.Length > 0 && tbNumer.Text.Length > 0 && tbEmail.Text.Length > 0)/
proponuję wydzielić do metody

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +                if (cbDataDo.Checked is true)
`if (cbDataDo.Checked)

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +                if (cbNrTelefonuDataDo.Checked is true)
jw

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +                if (cbEmailDataDo.Checked is true)
jw

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +                if (checkBox1.Checked is true)
proszę o nazwanie checkboxow

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionActivity.cs
> +            Czynnosc_produkcyjna czynnoscnew = new Czynnosc_produkcyjna();
camelCase

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionActivity.cs
> +            int id_czynnosc = int.Parse(this.dgvActivity.CurrentRow.Cells[0].Value.ToString());
camelCase

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionActivity.cs
> +            Czynnosc_produkcyjna czynnoscnew = new Czynnosc_produkcyjna();
prosze sie zdecydowac na język: polski lub angielski :)

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionByproduct.cs
> +            //dgvDataStart.DataSource = db.v_Proces_polprodukt_czynnosc_projekt.ToList();
do usunięcia

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionByproduct.cs
> +            //showData();
jw

2022-04-26 20:25 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionProduct.cs
> +        private void ComboBox()
nazwa metody z małej litery

2022-04-26 20:42 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +            if (tbPracownikNazwisko.Text.Length > 0 && tbPracownikImie.Text.Length > 0 && tbNrdowodu.Text.Length > 0 && tbPesel.Text.Length > 0 && tbNumer.Text.Length > 0 && tbEmail.Text.Length > 0)/
Naprawione

2022-04-26 20:42 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +                if (cbDataDo.Checked is true)
Naprawione

2022-04-26 20:42 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +                if (cbNrTelefonuDataDo.Checked is true)
Naprawione

2022-04-26 20:43 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +                if (cbEmailDataDo.Checked is true)
Naprawione

2022-04-26 20:43 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +                if (checkBox1.Checked is true)
Naprawione

2022-04-26 20:43 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormSetupProductionActivity.cs
> +            Czynnosc_produkcyjna czynnoscnew = new Czynnosc_produkcyjna();
Naprawione

2022-04-26 20:43 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormSetupProductionActivity.cs
> +            int id_czynnosc = int.Parse(this.dgvActivity.CurrentRow.Cells[0].Value.ToString());
Naprawione

2022-04-26 20:43 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormSetupProductionByproduct.cs
> +            //dgvDataStart.DataSource = db.v_Proces_polprodukt_czynnosc_projekt.ToList();
Naprawione

2022-04-26 20:43 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormSetupProductionByproduct.cs
> +            //showData();
Naprawione

2022-04-26 20:43 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormSetupProductionProduct.cs
> +        private void ComboBox()
Naprawione

2022-04-27 06:18 UTC, rudnickirobert requested changes

2022-04-27 06:18 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +            if (tbPracownikNazwisko.Text.Length > 0 && tbPracownikImie.Text.Length > 0 && tbNrdowodu.Text.Length > 0 && tbPesel.Text.Length > 0 && tbNumer.Text.Length > 0 && tbEmail.Text.Length > 0)/
proszę o wydzielenie do metody warunku w `if`

2022-04-27 06:18 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +            Dane_adresowe_pracownik dane_adresowe_pracownik = this.db.Dane_adresowe_pracownik.Single(b => b.ID_pracownik == dane);
camelCase

2022-04-27 06:18 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +            Nr_telefon_pracownik nr_telefon_pracownik = this.db.Nr_telefon_pracownik.Single(c => c.ID_pracownik == dane);
jw

2022-04-27 06:18 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +            Email_pracownik email_pracownik = this.db.Email_pracownik.Single(d => d.ID_pracownik == dane);
jw

2022-04-27 06:18 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +                Dane_adresowe_pracownik dane_adresowe_pracownik = new Dane_adresowe_pracownik();
jw

2022-04-27 06:50 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +            if (tbPracownikNazwisko.Text.Length > 0 && tbPracownikImie.Text.Length > 0 && tbNrdowodu.Text.Length > 0 && tbPesel.Text.Length > 0 && tbNumer.Text.Length > 0 && tbEmail.Text.Length > 0)/
Naprawione

2022-04-27 06:51 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +            Dane_adresowe_pracownik dane_adresowe_pracownik = this.db.Dane_adresowe_pracownik.Single(b => b.ID_pracownik == dane);
Naprawione

2022-04-27 06:51 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +            Nr_telefon_pracownik nr_telefon_pracownik = this.db.Nr_telefon_pracownik.Single(c => c.ID_pracownik == dane);
Naprawione

2022-04-27 06:51 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +            Email_pracownik email_pracownik = this.db.Email_pracownik.Single(d => d.ID_pracownik == dane);
Naprawione

2022-04-27 06:51 UTC, MGawron1998 commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerModify.cs
> +                Dane_adresowe_pracownik dane_adresowe_pracownik = new Dane_adresowe_pracownik();
Naprawione

2022-04-27 06:54 UTC, rudnickirobert requested changes

2022-04-27 06:54 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +                nrTelefonPracownik.Data_od = dnrod.Value;
czym jest `dnrod`?

2022-04-27 06:54 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentWorkerContractNew.cs
> +        private void CheckBox()
nazwa metody z małej litery, powinna też mówić co się w niej dzieje

2022-04-27 06:54 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionActivity.cs
> +        public void ShowData()
jw camelCase

2022-04-27 06:54 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionByproduct.cs
> +        private void ComboBox()
jw camelCase

2022-04-27 06:54 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormSetupProductionByproduct.cs
> +            //dgvDataStart.DataSource = db.v_Proces_polprodukt_czynnosc_projekt.ToList();
nadal widac

2022-04-27 07:22 UTC, rudnickirobert requested changes

2022-04-27 07:22 UTC, rudnickirobert commented on KWZP2022/KWZP2022/FormHRDepartmentNewWorker.cs
> +            if (tbPracownikNazwisko.Text.Length > 0 && tbPracownikImie.Text.Length > 0 && tbNrdowodu.Text.Length > 0 && tbPesel.Text.Length > 0 && tbNumer.Text.Length > 0 && tbEmail.Text.Length > 0)
`return tbPracownikNazwisko.Text.Length > 0 && tbPracownikImie.Text.Length > 0 && tbNrdowodu.Text.Length > 0 && tbPesel.Text.Length > 0 && tbNumer.Text.Length > 0 && tbEmail.Text.Length > 0;`

2022-04-27 07:23 UTC, rudnickirobert approved these changes

2022-04-27 07:23 UTC, merged